apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo-app1
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/example/app-of-app/webapp-1
    repoURL: https://github.com/mile9299/KubernetesApp.git
    targetRevision: main
